### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by djjudas21** [djjudas21/kubedownscaler#16]
Kubedownscaler crashes when the annotation has an empty value. Firstly need to make it handle this condition properly without crashing, secondly need to figure out how this condition arises. Seems like it often happens with deployments of Bitnami MariaDB.

```
jonathan@poseidon:~$ kubectl downscale -u -n paperless
Traceback (most recent call last):
  File "/home/jonathan/.local/bin/kubectl-downscale", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/jonathan/.local/lib/python3.13/site-packages/kubedownscaler/main.py", line 220, in main
    upscale(apps_v1, "Deployment", deployment, args.dry_run)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/.local/lib/python3.13/site-packages/kubedownscaler/main.py", line 93, in upscale
    original_replicas = int(
        obj.metadata.annotations['kubescaledown/originalReplicas'])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by djjudas21** [comment]
Fixed in #17
